Modified commandline tools; added commandline tools for direct SBtab …
tlubitz/SBtab pull request #101
Opened 2020-10-20 10:08 UTC by liebermeister

Hallo Timo,

vielen Dank nochmal für die (nochmalige) Erklärung mit den pull requests - ich hoffe ich habs jetzt verstanden!

ich hab etwas an den Kommandozeilenbefehlen gemacht: bei den existierenden Argumente für Ausgabedateinamen hinzugefügt und Kleinigkeiten geändert, und außerdem zwei neue Kommandaozeilenbefehle
(für SBtab <-> ObjTables-Konversion) geschrieben.

Viele Grüße
Wolf

2020-10-20 14:15 UTC, tlubitz commented
Hi Wolf,

ich schau es mir bald an, danke für den Pull Request. Technisch schon mal
sauber durchgeführt :)

Liebe Grüße,
Timo


Am Di., 20. Okt. 2020 um 12:09 Uhr schrieb Wolfram Liebermeister <
notifications@github.com>:

> Hallo Timo,
>
> vielen Dank nochmal für die (nochmalige) Erklärung mit den pull requests -
> ich hoffe ich habs jetzt verstanden!
>
> ich hab etwas an den Kommandozeilenbefehlen gemacht: bei den existierenden
> Argumente für Ausgabedateinamen hinzugefügt und Kleinigkeiten geändert, und
> außerdem zwei neue Kommandaozeilenbefehle
> (für SBtab <-> ObjTables-Konversion) geschrieben.
>
> Viele Grüße
> Wolf
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/tlubitz/SBtab/pull/101
> Commit Summary
>
>    - Modified commandline tools; added commandline tools for direct SBtab
>    <-> ObjTables conversion
>
> File Changes
>
>    - *A* python/sbtab_objtables2sbtab.py
>    <https://github.com/tlubitz/SBtab/pull/101/files#diff-6dcd689a37602a561835c392bdcaf1ce576c1da5e4c821818a408eeb87a05797>
>    (96)
>    - *M* python/sbtab_sbml2sbtab.py
>    <https://github.com/tlubitz/SBtab/pull/101/files#diff-1923183365dce306e9ced42589dd93cdd82b695760427f782521072571f4fb42>
>    (39)
>    - *M* python/sbtab_sbtab2html.py
>    <https://github.com/tlubitz/SBtab/pull/101/files#diff-930be087cfaf62a9d970e5f30c8a59dd451cc3f5cb9be028b7f3941db60b74b1>
>    (9)
>    - *A* python/sbtab_sbtab2objtables.py
>    <https://github.com/tlubitz/SBtab/pull/101/files#diff-d96c48dd7d3a37d66dca56b9873b06bbee0d29261fa23d9baa7b25b8be2b6884>
>    (107)
>    - *M* python/sbtab_sbtab2sbml.py
>    <https://github.com/tlubitz/SBtab/pull/101/files#diff-daa72b7175f1897aa26696833ede1ca4e07e24e20210a922e1c65691a0efaff5>
>    (26)
>
> Patch Links:
>
>    - https://github.com/tlubitz/SBtab/pull/101.patch
>    - https://github.com/tlubitz/SBtab/pull/101.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/tlubitz/SBtab/pull/101>, or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AGPUCF5TCFU5H6GLU2WJ6O3SLVOULANCNFSM4SYALIHA>
> .
>

2020-12-10 17:09 UTC, liebermeister commented
Hi Timo, 

ich hab jetzt die weiteren Änderungen gemacht. Ich hoffe, ich hab nichts zerschossen (und ich hoffe auch, dass ich nichts geändert habe, das jetzt Probleme in der online-Version macht). Wenn Du nochmal über die Änderungen reden möchtest, sag bitte Bescheid.

Danke und liebe Grüße
Wolf

2020-12-11 08:37 UTC, tlubitz requested changes
Hi Wolf,

insgesamt sieht das meiste dieses Commits gut aus! 2 kleine Punkte:

1. In Zeile 970 von SBtab.py rufst Du add_sbtab mit 3 Argumenten auf, es müssten aber eigentlich nur 2 sein. Ich glaube, das "None" in der Mitte hat sich da eingeschlichen, oder?
2. Bitte füge bei der Variablendeklaration zwischen Variable und Gleichheitszeichen immer nur EIN Leerzeichen ein. Wenn man stattdessen die Gleichheitszeichen alle untereinander schreibt, sieht das schön ordentlich aus, ist aber nicht so guter Programmierstil.

Bitte änder das noch und dann neuen Commit im Pull Request. Den Rest überlassen wir dann erstmal den Unit Tests.

2020-12-11 09:53 UTC, tlubitz approved these changes
Der erste Commit (vom 20.10.) sieht soweit gut aus!

2020-12-11 10:05 UTC, liebermeister commented
Ok ich hab die Änderungen gemacht. Danke!!

2020-12-11 12:49 UTC, merged